version: "3.8"

services:
   node_one:
      image: blockchain
      network_mode: host
      command: npm start -- -a localhost:8080 -o "localhost:8081 localhost:8082" -b 10
      ports:
           - "8080:8080"
   node_two:
      image: blockchain
      network_mode: host
      command: npm start -- -a localhost:8081 -o "localhost:8080 localhost:8082" -b 10
      ports:
         - "8081:8081"
   node_trhee:
      image: blockchain
      network_mode: host
      command: npm start -- -a localhost:8082 -o "localhost:8080 localhost:8081" -b 10 -g
      ports:
         - "8082:8082"