version: "3.8"

services:
   node1:
      image: blockchain
      container_name: node1
      command: npm start -- -a node1:7010 -o "node2:7010 node3:7010" -b 10
      ports:
           - "7010:7010"
   node2:
      image: blockchain
      container_name: node2
      command: npm start -- -a node2:7010 -o "node1:7010 node3:7010" -b 10
      ports:
         - "7011:7010"
   node3:
      image: blockchain
      container_name: node3
      command: npm start -- -a node3:7010 -o "node1:7010 node2:7010" -b 10 -g
      ports:
         - "7012:7010"